### ISSUE TITLE
Hello! Where can we download the Managed Solution ZIP for this "Easy History" PCF ? Thanks!

### ISSUE THREAD

**Issue by eeid7** [VinnyDyn/EasyHistory#1]
Hello! Where can we download the Managed Solution ZIP for this "Easy History" PCF ? Thanks!

**Comment by VinnyBasile** [comment]
Hi @eeid7
After my 3º PCF, all controls were added on [unique solution](https://github.com/VinnyDyn/StatusReasonKanban/releases) :)
