### ISSUE TITLE
While running in browser , we are facing issue and screenshot of the errors are attached

### ISSUE THREAD

**Issue by sharath1115** [VinnyDyn/EasyHistory#14]
![Xrm error](https://user-images.githubusercontent.com/65338748/134169553-bad50a9a-3bcc-4b28-a6f1-50b9fb927497.PNG)
![Xrm error1](https://user-images.githubusercontent.com/65338748/134169559-269d5e9c-3cad-4e3c-853d-a47bda067d44.PNG)

**Comment by VinnyBasile** [comment]
Hello @sharath1115 , the component can't be tested using npm start, because the audit history is retrieve using a custom action.
It is necessary you publish the solution.
